### ISSUE TITLE
Duplicitní záznamy

### ISSUE THREAD

**Issue by JarkaP** [LIBCAS/hiko#88]
při vytváření klíčových slov, profesí, identit a úložišť by mělo proběhnout ověření, zda už takový záznam neexistuje, aby se předešlo vytváření duplicit

- [x] identity (vyřešeno v #104) 
- [x] místa (vyřešeno v #108) 
- [x] profese (vyřešeno v #108) 
- [x] kategorie profesí (vyřešeno v #108) 
- [x] klíčová slova (vyřešeno v #105) 
- [x] kategorie klíčových slov (vyřešeno v #107) 
- [x] úložiště (vyřešeno v #109)
